const BAD_WORDS = [
  // ─── Groserías colombianas ────────────────────────────────────────────────
  "mierda",
  "hijueputa",
  "hijueputas",
  "puta",
  "putas",
  "puto",
  "putos",
  "marica",
  "gonorrea",
  "malparido",
  "malparida",
  "hp",
  "ctm",
  "culero",
  "pendejo",
  "pendeja",
  "pendejada",
  "idiota",
  "estupido",
  "estupida",
  "imbecil",
  "huevon",
  "huevona",
  "hijomane",
  "maldito",
  "maldita",
  "desgraciado",
  "desgraciada",
  "careculo",
  "carepicha",
  "verga",
  "maricada",
  "saporro",
  "mondá",
  "mondá",
  "perras",
  "perra",

  // ─── Sexual explícito ─────────────────────────────────────────────────────
  "sexo",
  "sexual",
  "porno",
  "pornografia",
  "pornográfica",
  "xxx",
  "oral",
  "anal",
  "vagina",
  "pene",
  "penis",
  "culo",
  "culos",
  "tetas",
  "tetona",
  "nalgas",
  "nalga",
  "prostituta",
  "prostitución",
  "escort",
  "prepago",
  "desnudo",
  "desnuda",
  "desnudos",
  "erótico",
  "erotica",
  "masturbacion",
  "masturbarse",
  "coger",
  "follar",
  "relaciones",
  "intimas",
  "onlyfans",
  "webcam",
  "stripper",

  // ─── Drogas y sustancias ──────────────────────────────────────────────────
  "cocaina",
  "cocaine",
  "marihuana",
  "cannabis",
  "droga",
  "drogas",
  "heroina",
  "crack",
  "bazuco",
  "meth",
  "metanfetamina",
  "lsd",
  "narcotráfico",
  "narco",
  "cartel",

  // ─── Violencia y amenazas ─────────────────────────────────────────────────
  "matar",
  "mátate",
  "muerte",
  "asesinar",
  "asesino",
  "asesina",
  "violar",
  "violacion",
  "secuestrar",
  "secuestro",
  "bomba",
  "terrorismo",
  "terrorista",
  "sicario",

  // ─── Spam y estafa ────────────────────────────────────────────────────────
  "bitcoin",
  "crypto",
  "inversion garantizada",
  "gana dinero facil",
  "hacerse rico",
  "multinivel",
  "piramide",
];

function containsBadWords(text) {
  if (!text) return false;
  const normalized = text.toLowerCase().replace(/[^a-záéíóúüñ\s]/gi, " ");
  return BAD_WORDS.some((word) => {
    const regex = new RegExp(`\\b${word}\\b`, "i");
    return regex.test(normalized);
  });
}

module.exports = { containsBadWords, BAD_WORDS };
